### PR TITLE
TESTENG-1565: Add Code of Conduct

### PR DESCRIPTION
**Pull request by Sai-Nissankula**
Complete the following tasks before merging in your PR:
- [x] If this is a user facing change, update [version.txt](https://github.com/relativitydev/relativity.testing.framework.api/blob/master/version.txt) and [CHANGELOG.md](https://github.com/relativitydev/relativity.testing.framework.api/blob/master/CHANGELOG.md)

### CODE REVIEW

**Comment by Sai-Nissankula** [comment]
This is just a copy+paste of the conduct from RTF repo.

**Comment by paulletang** [comment]
> > How was this merged in before the checks were complete?
> 
> I think all of us are admins on this repo, with the power to ignore checks when merging.

It's not that, but I figured it out.
You can specify status that need to pass before merging in.
I thought that `Build` meant the entire build workflow, but that's not the case.

I just added the test stages to the list of ones that need to complete.
image

**Comment by Sai-Nissankula** [comment]
I merged it in without waiting because it was just a md file and doesnt touch any code.

**Comment by paulletang** [comment]
> I merged it in without waiting because it was just a md file and doesnt touch any code.

I get that it's not touching the code, but that's an ability that I don't want users in this codebase to have.
If undermines the idea of CD if you someone can decide to not adhere to those checks.

**Pull request merged**
