### PR TITLE
REL-598943 Disable Signed Modules in Windsor

### PR DESCRIPTION
**Pull request by joe-buschmann-relativity**
Complete the following tasks before merging in your PR:
- [x] If this is a user facing change, update [version.txt](https://github.com/relativitydev/relativity.testing.framework.api/blob/master/version.txt) and [CHANGELOG.md](https://github.com/relativitydev/relativity.testing.framework.api/blob/master/CHANGELOG.md)

### CODE REVIEW

**Comment by joe-buschmann-relativity** [comment]
I can't upgrade Polly to latest in my functional test project because Windsor in the RTF expects version 5.7.0. This PR loosens that restriction so test projects can upgrade dependencies that are shared with the RTF as long as they're compatible.

**Comment by briantoms** [comment]
Created #259 as a local branch to run functional tests.

**Comment by joe-buschmann-relativity** [comment]
Per @paulletang, I will close this PR and open one directly against the repository.

**Comment by joe-buschmann-relativity** [comment]
NVM, reopening. :)

**Review by paulletang — APPROVED** [review]
Tests look good.
This is ready to merge.

**Review by briantoms — APPROVED** [review]
Tests passed on #259.

**Comment by joe-buschmann-relativity** [comment]
Cool, I deleted the fork.

**Pull request merged**
