### PR TITLE
Polly Upgrade to v7.2.2

### PR DESCRIPTION
**Pull request by joe-buschmann-relativity**
Complete the following tasks before merging in your PR:
- [x] If this is a user facing change, update [version.txt](https://github.com/relativitydev/relativity.testing.framework.api/blob/master/version.txt) and [CHANGELOG.md](https://github.com/relativitydev/relativity.testing.framework.api/blob/master/CHANGELOG.md)

### CODE REVIEW

**Comment by briantoms** [comment]
Why do we need to upgrade Polly? Is there a security vulnerability in Polly v5.7.0?

**Comment by joe-buschmann-relativity** [comment]
I added a reference to Polly v7.2.2 to my functional test project which uses the RTF. My build failed saying it couldn't find Polly v5.7.0. I tried adding a binding redirect with no luck. v7.2.2 has a public key token whereas v5.7.0 does not. See https://stackoverflow.com/questions/2191296/net-assembly-binding-redirect-with-differing-public-key-tokens

I'd like to use new features in v7.2.2 with better support for async/await.

**Comment by briantoms** [comment]
My understanding is that this is going to force everyone using RTF.API to update their Polly version when updating RTF.API, and there seem to be some breaking changes between the two Polly versions (as indicated by the major version bump). I'm not necessarily opposed to this change, but I'd like for others on the team to weigh in.

There's also an issue where the functional tests don't run when a user in the `relativitydev` organization creates a PR from a fork, and I'd want to see passing tests before merging this in. I believe we had a workaround for this, but I'll have to find it.

**Comment by joe-buschmann-relativity** [comment]
Good point on the breaking changes. Perhaps a major version bump is more appropriate?

**Comment by briantoms** [comment]
> Good point on the breaking changes. Perhaps a major version bump is more appropriate?

SemVer says only to bump the major version when making breaking changes to your _own_ APIs, not to dependencies.

**Comment by amk334** [comment]
Try adding this to the container Install method. Otherwise it strongly names the dependencies that get registered. Which is why it really wants 5.7.0.0.

container.Kernel.ProxyFactory = new DefaultProxyFactory(disableSignedModule: true);

Other teams run into this for Relativity.Kepler.dll in their own WindsorContainers while running their tests which is why we know about it.

Pretty sure you can add it as the first line of this Install method before registering things.
https://github.com/relativitydev/relativity.testing.framework.api/blob/e8b2a7e1f35[…]4e60e2f/source/Relativity.Testing.Framework.Api/ApiComponent.cs

Example
https://git.kcura.com/projects/DTX/repos/relativity-data-transfer-legacy-sdk/browse[…]ce/DataTransfer.Legacy.Services/Installer/ServicesInstaller.cs (edited)

**Comment by joe-buschmann-relativity** [comment]
Closing due to the risk of updating Polly. Instead, I'll have a new PR up shortly with @amk334's suggested fix. His is the better long term approach.

**Pull request closed without merging**
