### PR TITLE
RTF-1433: update supported version range

### PR DESCRIPTION
**Pull request by Sai-Nissankula**
Complete the following tasks before merging in your PR:
- [x] If this is a user facing change, update [version.txt](https://github.com/relativitydev/relativity.testing.framework.api/blob/master/version.txt) and [CHANGELOG.md](https://github.com/relativitydev/relativity.testing.framework.api/blob/master/CHANGELOG.md)

### CODE REVIEW

**Review by katiesapede — DISMISSED** [review]

**Comment by Sai-Nissankula** [comment]
I am not sure, do we? What was the process for that again?

**Comment by briantoms** [comment]
> I am not sure, do we? What was the process for that again?

It involves updating the GitHub Actions files for feature branch and release branch. I assume there's no Hopper for 13.2, but we should have one for 13.1 (White Sedge) by now if I'm understanding the calendar correctly.

**Review by briantoms — APPROVED** [review]
While we're in here, we can also update to the latest Hopper templates for Sundrop and Tiger Lily.

**Comment by Sai-Nissankula** [comment]
The logs look like there is a breaking change in one of the APIs in WhiteSedge?

**Comment by Sai-Nissankula** [comment]
> While we're in here, we can also update to the latest Hopper templates for Sundrop and Tiger Lily (and Osier, if there's a new template for Server 2022).

Sure I can update those.

**Comment by briantoms** [comment]
> The logs look like there is a breaking change in one of the APIs in WhiteSedge?

Yeah, there might be an Import API issue. Though I would have expected to hear about problems sooner, since that version has already been used in Ring 0 environments...

**Review by briantoms — APPROVED** [review]

**Pull request merged**
